# Generated by Django 3.2.5 on 2022-03-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
