# Generated by Django 3.2.5 on 2022-03-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_path_visitor_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
