# Generated by Django 3.2.5 on 2022-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visitor_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='proccess_time',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
