# Generated by Django 3.2.5 on 2022-03-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_visitor_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='region',
            new_name='country_code',
        ),
    ]
