# Generated by Django 3.2.5 on 2021-09-27 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_visitor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
