# Generated by Django 3.2.5 on 2022-03-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_token_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
